Algolia.Search/AlgoliaClient.cs

In this change b331b344f3f6a458a8c8187ffe442ae2089cc242 from
an onlyErrors option on the endpoint to type the parameter name
was not changed

fix log parameter type

---

Algolia.Search.Test/AlgoliaClientTest.cs
Algolia.Search.Test/BaseTest.cs
Algolia.Search/Algolia.Search.csproj
Algolia.Search/AlgoliaClient.cs
Algolia.Search/Index.cs
Algolia.Search/IndexHelper.cs
Algolia.Search/Models/RequestOptions.cs
Algolia.Search/Models/RuleQuery.cs
Algolia.Search/Query.cs
ChangeLog

- Create RequestOptions class
- Change the way we send the http request from [client.{action}Async](https://github.com/algolia/algoliasearch-client-csharp/compare/request-options?expand=1#diff-3c0743ed790b438e879144d8670f9ea4L1109) to [client.sendAsync](https://github.com/algolia/algoliasearch-client-csharp/compare/request-options?expand=1#diff-3c0743ed790b438e879144d8670f9ea4R1150) in order to add extra headers. The reason is because we can't add custom headers per request when doing client.{Get/Post/Put/Delete}Asnyc.
- Add request options to all methods
- Tests work locally, issue is known about 2 tests not working on appveyor due to some key permission problem. @CBaptiste will take a look

Add request options as optional parameters to all methods

---

Algolia.Search.Test/AlgoliaClientTest.cs
Algolia.Search/Index.cs

Not sure if I missed to add some tests or even if it's the appropriate way of doing it. All comments are most welcome :)

fix: Prevent saving a rule with an empty objectID

---

Algolia.Search.Test/AlgoliaClientTest.cs
Algolia.Search/Index.cs

Cursor can get very long and exceed the max url size, for that reason we always pass it in the body of the request.
Note: In case there is no params (if you use $query = null) we fallback on a GET call since the API doesn't allow empty bodies for POST.

fix(browse): Ensure cursor is passed in the body

---

Algolia.Search/AlgoliaClient.cs
Algolia.Search/AlgoliaException.cs

| Related Issue     | Fix #525
Expose the raw HttpStatusCode on the algoliaException, making it possible to compare to 429 in the case of rate limit. Another way would be to wrap this in a subclass of AlgoliaException, e.g. AlgoliaRateLimitException.
Makes it possible to find out if we're currently rate limited.

Expose the raw HttpStatusCode on the AlgoliaException object.

---

src/Algolia.Search.Test/EndToEnd/Index/IndexingTest.cs
src/Algolia.Search/Clients/SearchIndex.cs

| Related Issue     | Fix #535 
Fixed `DeleteObject` URI.
`DeleteObject` not working as expected.

Fixed: deleteObject wrong URI

---

src/Algolia.Search.Test/EndToEnd/Index/IndexingTest.cs
src/Algolia.Search/Utils/AlgoliaHelper.cs

| Related Issue     |  #536 #539 
An error when using `SaveObjects` with a POCO that have `ObjectID` in a base class.
Added a `GetAllProperties` method in `AlgoliaHelper` that is able to check that a base class has a `
ObjectID` property.

Fixed: EnsuredObjectID not working with POCO base class

---

src/Algolia.Search.Test/EndToEnd/ApiKeys/SecuredApiKeyTest.cs
src/Algolia.Search/Models/Search/FacetStats.cs
src/Algolia.Search/Models/Search/SearchResponse.cs

| Related Issue     | Fix #542 
Added the missing parameters in `SearchResponse`
* Facets
* FacetsStats
* UserData
* AppliedRules

Adding missing parameter in SearchResponse

---

src/Algolia.Search/Models/Search/SearchForFacetRequest.cs

| Related Issue     | Fix #547 
The `SearchParameters` property in `SearchForFacetRequest` should have a `[JsonProperty(PropertyName = "params")]` instead of ` [JsonProperty(PropertyName = "requests")]`.
[Doc link.](https://www.algolia.com/doc/rest-api/search/?language=php#method-param-params-2)

Fixed: JsonPropertyName of SearchForFacetRequest

---

src/Algolia.Search/Clients/InsightsClient.cs

| Related Issue     | Fix #546 
Fixed the CallType of `SendEvents`. From read to write.

Fixed: calltype (read -> write) of SendEvents

---

src/Algolia.Search/Models/Search/SearchResponse.cs

| Related Issue     | Fix #551
Correct JSON property name and correct type to Dictionary<string, FacetStats>
#551 not returning facet stats on 6.x.x

Fixed: Facet Stats

---

src/Algolia.Search/Algolia.Search.csproj

Updated the logo URL because the actual one is now returning a 404 since static website update.
@aseure Any idea if we could get back the old URL back? I need to upload a new minor version of the package to upload the link.

Fixing: package logo URL

---

src/Algolia.Search.Test/EndToEnd/Index/MultiClusterManagementTest.cs
src/Algolia.Search/Clients/SearchClient.cs
src/Algolia.Search/Models/Mcm/AssignUserIdResponse.cs
src/Algolia.Search/Models/Mcm/RemoveUserIdResponse.cs

| Bug fix?          | #564 
The Wait() helper method for MCM was not reliable enough, so with the team we decided to remove it.

Removed: Wait() method for MCM

---

src/Algolia.Search/Models/Search/Query.cs

Adding missing `userToken` parameter in the `Query` class.

Added: missing userToken parameter in Query

---

src/Algolia.Search/Models/Search/HighlightResult.cs
src/Algolia.Search/Models/Search/SnippetResult.cs

| Related Issue     | Fix #583 
Adding missing models for `SnippetResult` and `HighlightResult`

Added: SnippetResult and HighlightResult

---

src/Algolia.Search/Models/Search/AroundPrecision.cs
src/Algolia.Search/Models/Search/Query.cs

| BC breaks?        | yes      
| Related Issue     | Fix #578 
The query parameter `AroundPrecision` can now handle the following JSON format:
```json
{"aroundPrecision":[{"from":0, "value":10}, {"from":100, "value":1000}]}
```
Added the `AroundPrecision` poco and modified the `Query` class to allow the library to handle the updated parameter.

Updated: AroundPrecision search param

---

src/Algolia.Search.Test/EndToEnd/Index/SettingsTest.cs
src/Algolia.Search.Test/Serializer/SerializerTest.cs
src/Algolia.Search/Models/Search/Query.cs
src/Algolia.Search/Models/Settings/IndexSettings.cs

Adds the possibility to the users to add custom parameters to `Query` and `IndexSettings`.

Added: custom parameters to Query and Settings

---

src/Algolia.Search.Test/Serializer/SerializerTest.cs
src/Algolia.Search/Utils/QueryStringHelper.cs

The ToQueryString() method was not writing nested arrays as expected
causing MultipleQueries with nested arrays to return wrong responses.
Expected format:
`query=&facetFilters=[["facet1:true"],["facet2:true"]]`
`query=&facetFilters=[["facet1:true","facet2:true"],["facet3:true"]]`
`query=&facetFilters=[["facet1:true"]]`

Fixed: Query serializer with nested Arrays

---

src/Algolia.Search/Transport/HttpTransport.cs
src/Algolia.Search/Utils/Defaults.cs

This fixes a typo in the code (`WriteTimeut` → `WriteTimeout`).

fix: fix typo (WriteTimeut → WriteTimeout)

---

src/Algolia.Search.Test/EndToEnd/Index/ExistsTest.cs
src/Algolia.Search/Clients/ISearchIndex.cs
src/Algolia.Search/Clients/SearchIndex.cs

| New feature?      | yes    
| Related Issue     | Fix #625  
This adds the `SearchIndex.Exists` method in the client. It follows the [spec](https://github.com/algolia/algoliasearch-client-specs/blob/master/features/index-exists.md) and [common test suite](https://github.com/algolia/algoliasearch-client-specs/tree/master/common-test-suite#Exists).

feat(index): add exists method

---

src/Algolia.Search.Test/BaseTest.cs
src/Algolia.Search/Clients/AlgoliaConfig.cs
src/Algolia.Search/Clients/InsightsConfig.cs
src/Algolia.Search/Clients/SearchConfig.cs
src/Algolia.Search/Http/AlgoliaHttpRequester.cs
src/Algolia.Search/Http/HttpRequestHeadersExtensions.cs
src/Algolia.Search/Models/Common/Request.cs
src/Algolia.Search/Models/Enums/CompressionType.cs
src/Algolia.Search/Serializer/SerializerHelper.cs
src/Algolia.Search/Transport/HttpTransport.cs
src/Algolia.Search/Utils/Defaults.cs

| Related Issue     | Fix #621

Added: GZip compression feature (#621)

---

src/Algolia.Search.Test/RetryStrategyTest/RetryStrategyTest.cs
src/Algolia.Search/Http/AlgoliaHttpRequester.cs
src/Algolia.Search/Http/AlgoliaHttpResponse.cs
src/Algolia.Search/Transport/HttpTransport.cs
src/Algolia.Search/Transport/RetryStrategy.cs

The `AlgoliaHttpRequester` was not catching correctly all exceptions, making the retry strategy to fail for a specific network exception instead of retrying. In fact, the `RetryStrategy` was not retrying for retryable failures such as DNS failure, server certificate validation.

fix: missing catch clause in httpRequester

---

src/Algolia.Search.Test/RetryStrategyTest/RetryStrategyTest.cs

Fixed a glyph in `TestRetryStrategyRetriableFailure`

fixed: retryStrategy test for retriable failure

---

src/Algolia.Search.Test/EndToEnd/Index/SettingsTest.cs
src/Algolia.Search/Models/Settings/IndexSettings.cs

| Related Issue     | Fix #636
Implement the new `indexLanguages` setting which is an array of strings.
Currently, only `["ja"]` is supported by the engine.

Feat(indexLanguages)

---

src/Algolia.Search.Test/EndToEnd/Index/QueryRulesTest.cs
src/Algolia.Search/Models/Rules/Alternatives.cs
src/Algolia.Search/Serializer/AlternativesConverter.cs

| Related Issue     | Fix #637 
This PR adds the`Alternatives` parameter in QueryRules conditions
Alternatives may transform into JSON object in the future.
That's why it comes with a customer serializer and
an abstract factory.

feat(queryRules/alternatives)

---

src/Algolia.Search.Test/Serializer/SerializerTest.cs
src/Algolia.Search/Models/Search/Query.cs
src/Algolia.Search/Serializer/FiltersConverter.cs

Legacy form of `filters` were not supported by the JsonReader.
one string legacy filters `"color:green,color:yellow"` are converted
to "ORED" nested filters `[["color:green","color:yellow"]]`
array legacy filters [`"color:green","color:yellow"]` are converted
to "ORED" nested filters `[["color:green","color:yellow"]]`

Fix(JsonReader/LegacyFIlters)

---

src/Algolia.Search/Models/Synonyms/SynonymQuery.cs

Fixed the type of "SynonymQuery.Type". It's now a String instead
of a List<string>.
For example: Type =  "synonym,oneWaySynonym,placeholder"

fix: Type in synonym query is now a String instead String[]

---

src/Algolia.Search/Http/AlgoliaHttpRequester.cs
src/Algolia.Search/Models/Enums/CompressionType.cs
src/Algolia.Search/Serializer/DefaultSerializer.cs
src/Algolia.Search/Serializer/ISerializer.cs
src/Algolia.Search/Transport/HttpTransport.cs

| Need Doc update   | not yet
This commit is adding the `ISerializer` interface to anticipate different
implementations of the latter.
With the upcoming support of .NET Core 3 the library will support
both `Newtonsoft.JSON` and `System.Text.Json`
`ISerializer` will allow us to switch between both implementations
more easily with the help of pre-processor:
```csharp
#IF NETCOREAPP3_0
System.Text.Json
#ELSE
Newtonsoft.JSON
#ENDIF
```

internal: ISerializer interface

---

azure-pipelines.yml
src/Algolia.Search.Test/Algolia.Search.Test.csproj
src/Algolia.Search/Algolia.Search.csproj

| Related Issue     | Fix #651 
This PR is adding support for `.NET Standard 2.1` and `.NET Core 3`.
Another PR will take care of adding the new std JSON Serializer

feat:Bump library to .NET Standard 2.1 / .Net Core 3

---

src/Algolia.Search/Models/Search/Alternative.cs
src/Algolia.Search/Models/Search/Explain.cs
src/Algolia.Search/Models/Search/Query.cs
src/Algolia.Search/Models/Search/QueryMatch.cs
src/Algolia.Search/Models/Search/SearchResponse.cs

| Related Issue     | Fix #674 
- adds `Explain` parameter in `Query`
- adds `Explain` response property in `SearchResponse`
Waiting for CTS test and better documentation before merging.

feat(query): explain decompounding at query time

---

src/Algolia.Search.Test/Serializer/SerializerTest.cs
src/Algolia.Search/Models/Rules/ConsequenceParams.cs
src/Algolia.Search/Models/Rules/ConsequenceQuery.cs
src/Algolia.Search/Serializer/ConsequenceQueryConverter.cs

[changelog]
Fixed: Custom serializer to handle polymorphism of "query" attribute
in ConsequenceQuery
Example:
```json
// query string
"query": "some query string"
// remove attribute (deprecated)
"query": {"remove": ["query1", "query2"]}
// edits attribute
"query": {
"edits": [
{ "type": "remove", "delete": "old" },
{ "type": "replace", "delete": "new", "insert": "newer" }
]
}}
```json

patch: serialization/deserialization of ConsequenceQuery

---

src/Algolia.Search/Models/Analytics/ABTest.cs

`abTestId` in ABTest should be `abTestID`.However, NewtonSoft is silently converting it correctly. This is a preventive fix in case this behavior evolves in the feature

fix: abTestID casing in ABTest

---

azure-pipelines.yml

Azure pipelines recently declared they were about to drop macOS 10.13
from their image pool. This commit hence update the macOS build for our
tests from macOS 10.13 to macOS 10.15, which is the most recent available
version at the moment.

chore(ci): update macOS image for Azure pipelines from 10.13 to 10.15

---

src/Algolia.Search/Utils/QueryStringHelper.cs

| Related Issue     | Fix #694 Fix #695 Fix #696 
Separators `;` is no longer allowed for `restrictSources` and `restrictIndices`
For the record, Java is fixed as well:
https://github.com/algolia/algoliasearch-client-java-2/commit/4a8e356ca494c49505341e88be8aed950741df07

fix(apiKey): bad separator for restrictSources/restrictIndices

---

src/Algolia.Search/Models/Common/LogResponse.cs

| Bug fix?          | yes/no
| Related Issue     | Fix #700 
Add the new `inner_queries` response field in GetLogs
```json
"inner_queries": [
{
"index_name": "indexName",
"query_id": "313453231",
"offset": 0,
"user_token": "user1"
}
]
```

feat(logs): adds inner_queries

---

.circleci/config.yml

This commit ensure that the message shows the name of the missing
environment variable *without* expanding it in the shell during the CI
release step.

chore(ci): fix an error display message in release step

---

src/Algolia.Search.Test/EndToEnd/Index/IndexingTest.cs
src/Algolia.Search/Clients/SearchIndex.cs
src/Algolia.Search/Utils/AlgoliaHelper.cs

| New feature?      | yes/no   
| Related Issue     | Fix #654
This commit adds additional check in the PartialUpdateObject() method, to allow JObject as parameter.

fix: PartialUpdateObject() throwing "data should not be IEnumerable" with JObject

---

src/Algolia.Search.Test/EndToEnd/Index/IndexingTest.cs

| Related Issue     | Fix [here](https://github.com/algolia/algoliasearch-client-specs-internal/pull/140)  
Update the CTS indexing test
Following the new test : 
- Add tagged object 
- Delete tagged object

tests: Add delete by tag CTS test

---

src/Algolia.Search.Test/RetryStrategyTest/ExceptionsTests.cs
src/Algolia.Search/Http/AlgoliaHttpRequester.cs
src/Algolia.Search/Transport/HttpTransport.cs

| New feature?      | no   
| Related Issue     | Fix #737  
- Send Error message to the transport layer
- Save last error message and add it in the Exception
When all hosts are down the SDK sends the All hosts are unreachable message which is unclear. We would like to send the underlying error message to ease debugging.

Fix: Improve unreachable host error message

---

src/Algolia.Search.Test/EndToEnd/Analytics/AnalyticsAbTest.cs
src/Algolia.Search/Models/Analytics/Variant.cs

| New feature?      | yes  
| Related Issue     | Fix [#142](https://github.com/algolia/algoliasearch-client-specs-internal/pull/142)  
| Need Doc update   | no ( already done )
Add the field trackedSearchCount to AB testing metrics returned.

feat(analytics): add tracked search count

---

src/Algolia.Search.Test/RetryStrategyTest/RetryStrategyTest.cs
src/Algolia.Search/Transport/HttpTransport.cs

| Bug fix?          | YES
Following on a expired certificate issue on one of `-dsn` domains, we noticed that in some cases, the C# client wasn't able to correctly retry a failing call. 
In that case the exception sent was:
```
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. 
---> System.Security.Authentication.AuthenticationException: 
The remote certificate is invalid according to the validation procedure.
```
This SSL exception thrown by the `httpClient` was correctly catched and marked as a retryable failure by the strategy, but the following retry calls failed with the following exception:
``` …
```

fix(transport): MemoryStream disposed betweem two retryStrategy call

---

src/Algolia.Search/Serializer/DefaultSerializer.cs

In `src/Algolia.Search/Serializer/DefaultSerializer.cs`, let's have a re-usable instance of `JsonSerializer`  instead of a creating one for each call.  This will allow NewtonSoft to re-use  `JsonContract` instead of recreating one for each call.
Performance issue under high load. See perf impact before and after the fix:
Before:
After:

feat(serializer): JsonSerializer re-usable instance

---

src/Algolia.Search.Test/EndToEnd/Index/IndexingTest.cs
src/Algolia.Search/Clients/SearchIndex.cs

| Related Issue     | Fix #757  
- Instantiate DeleteResponse and wait on it
- Add tests
Calling Index.Delete().Wait() throws null reference exception.

Fix : delete index method to be waitable

---

src/Algolia.Search.Test/EndToEnd/Client/ApiKeysTest.cs

| BC breaks?        | no    
| Related Issue     | Fix #734 
This pull request is related to our API Key test that is flaky. 
This is fixing our Test suits issues where we need to run multiple time our CI or our local test before this test pass.

Fix: TestApiKey flakiness

---

src/Algolia.Search/Models/Search/Query.cs
src/Algolia.Search/Models/Search/SearchResponse.cs
src/Algolia.Search/Models/Settings/IndexSettings.cs

| New feature?      | yes    
| Related Issue     | Fix #759   
Search query &  index Settings parameters:
* **relevancyStrictness** 
- integer value [0-100]  
- relevancy score to apply to search in virtual index. Bigger value means less, but more relevant results, lesser value - more less relevant results
Search response:
* **appliedRelevancyStrictness** 
- integer value [0-100]
- relevancy score to apply to the search in virtual index. 
* **nbSortedHits** 
- integer value
- number of relevant hits to display in case of non-zero `relevancyStrictness` applied

feat(settings): relevant sorting

---

src/Algolia.Search.Test/EndToEnd/Index/SettingsTest.cs
src/Algolia.Search.Test/Serializer/SerializerTest.cs
src/Algolia.Search/Models/Settings/IndexSettings.cs

| Related Issue     | 
- Include null for NewtonSoft on `NumericAttributesForFiltering` parameter.
- Add the method [ShouldSerialize](https://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_Serialization_JsonProperty_ShouldSerialize.htm) from newtonsoft to avoid serialize empty field.
- Add a dedicated setter for `NumericAttributesForFiltering`. 
- Add tests with `null` for `NumericAttributesForFiltering`
Our C# client is using newtonsoft.json to serialize our parameter. This serializer is configurable and for the C# client we exclude null field in our request. However for a specific attribute on settings …

Fix: add custom setter for NumericAttributesForFiltering

---

src/Algolia.Search/Models/Common/ListIndicesResponse.cs

| New feature?      |yes    
Adds missing fields to `IndicesResponse`:

feat(indices: add missing field to IndicesResponse

---

src/Algolia.Search.Test/Serializer/SerializerTest.cs
src/Algolia.Search/Models/Search/Query.cs

| New feature?      | yes   
| Related Issue     | [spec-internal](https://github.com/algolia/algoliasearch-client-specs-internal/issues/164)
Add query parameter : enableReRanking
This was on the documentation but not implemented on the client
-> https://www.algolia.com/doc/api-reference/api-parameters/enableReRanking/?client=csharp

Feat(query): add enableReRanking query parameter

---

src/Algolia.Search.Test/EndToEnd/Index/QueryRulesTest.cs
src/Algolia.Search/Models/Rules/ConsequencePromote.cs

This adds `objectIDs` to the `ConsequencePromote` class to allow boosting multiple objectIDs at once.

feat(rules): add ObjectIDs to ConsequencePromote

---

src/Algolia.Search.Test/EndToEnd/Analytics/AnalyticsAATest.cs
src/Algolia.Search.Test/EndToEnd/Analytics/AnalyticsAbTest.cs
src/Algolia.Search/Clients/AnalyticsClient.cs
src/Algolia.Search/Clients/IAnalyticsClient.cs
src/Algolia.Search/Models/Analytics/ABTest.cs
src/Algolia.Search/Models/Analytics/AddABTestRequest.cs
src/Algolia.Search/Models/Analytics/Variant.cs

| Related Issue     | Fix # [here](https://github.com/algolia/algoliasearch-client-specs-internal/issues/146)
- Update key which aren't nullable
- New `AddABTestRequest` which exposes only the needed properties to send when creating an ABTest
Some properties have been marked as nullable to not been sent in the request, but are always present in the response. To improve DX, let's separate the request from the actual `ABTest` object.

fix: ab test nullability keys

---

src/Algolia.Search.Test/Serializer/SerializerTest.cs
src/Algolia.Search/Models/Search/PartialUpdateOperation.cs

| Related Issue     | #775
Make built-in operations 'IncrementFrom' and 'IncrementSet' usable with `long`

feat: support `long` in IncrementSet/IncrementFrom

---

.gitignore
src/Algolia.Search.Test/Serializer/SerializerTest.cs
src/Algolia.Search/Serializer/FiltersConverter.cs

| Related Issue     | https://github.com/algolia/algoliasearch-client-java-2/pull/771
Port the fix already made in the Java client: https://github.com/algolia/algoliasearch-client-java-2/pull/771
> Fixes `optionalFilters` deserialization for following special cases: 
> * `["A:1", "B:2"]` ->   `[["A:1"], ["B:2"]]`
> * `"A:1", "B:2"`  ->   `[["A:1"], ["B:2"]]`

fix: optional filters deserialization

---

src/Algolia.Search/Clients/SearchIndex.cs

I have already some preformatted JSON and I would like to avoid to serialize it again and then deserialize it. There the JRaw support.
| New feature?      | yes (very small)
| Related Issue     | Fix #...  
I would like to send preformatted JSON to algolia, without deserializing and serializing it again.
Newtonsoft JRaw supports that fine.

Support preformatted json.

---

src/Algolia.Search.Test/Utils/AlgoliaHelperTest.cs
src/Algolia.Search/Utils/AlgoliaHelper.cs

| Related Issue     | Fix #815
Reported by [jsancho](https://github.com/jsancho) in #815:
When called with a `JObject`, the `AlgoliaHelper.GetObjectID()` method was returning `"\"objectID\": \"my-object-id\""` instead of the objectID, making methods relying on it not working properly.

fix: AlgoliaHelper.GetObjectID

---

CHANGELOG.md
src/Algolia.Search/Algolia.Search.csproj
src/Directory.Build.props

| Related Issue     | 
The purpose of this change is to push debug symbols as a separate **.snupkg** to [NuGet.org](https://www.nuget.org/packages/Algolia.Search/).
This package can be retrieved by IDE (Visual Studio, VS Code) during debug, enabling stepping into source code with the help of SourceLink.
Using latest snupkg format.
ContinuousIntegrationBuild should be set during CI to avoid linking to paths from build vm, but not when built manually where local paths are relevant. (I couldn't easily test this part as I don't have access to a CircleCI platform, I am assuming that env variable CIRCLECI is set during CI)
Command …

Add SourceLink and push symbols to NuGet.org

---

src/Algolia.Search/Models/Search/SearchResponse.cs

| New feature?      | no  
| Related Issue     | 
If `GetRankingInfo`is set to `true` in the `Query`, then the property `AbTestID` should be available. That wasn't correctly done.
Missing `AbTestID` property in the `SearchResponse`.

fix(search): add missing AbTestID property

---

src/Algolia.Search.Test/Serializer/SerializerTest.cs
src/Algolia.Search/Models/Search/Query.cs

Add a missing property in `Query` object.
`QueryLanguages` property was not part of the `Query`.

fix: add QueryLanguages to Query
