Algolia.Search/Algolia.Search.csproj
Algolia.Search/AlgoliaClient.cs
Algolia.Search/Utils/ArrayHelper.cs

Signed-off-by: CBaptiste <coquellebaptiste@gmail.com>

shuffling read and write hosts

---

Algolia.Search/Query.cs

when float= X.XXf float.toString changes to the culture of the string

fix issue on float.tostring conversion

---

Algolia.Search/Algolia.Search.nuspec
Algolia.Search/Properties/AssemblyInfo.cs
ChangeLog

Bump to 3.6.2

---

Algolia.Search.Test/AlgoliaClientTest.cs
Algolia.Search/Algolia.Search.csproj
Algolia.Search/Models/AllRadius.cs
Algolia.Search/Models/RemoveStopWords.cs
Algolia.Search/Query.cs

Signed-off-by: CBaptiste <coquellebaptiste@gmail.com>

Support to RemoveStopWords and AllRadius

---

Algolia.Search.Test/AlgoliaClientTest.cs
Algolia.Search.Test/BaseTest.cs
Algolia.Search/Iterators/RulesIterator.cs
Algolia.Search/Iterators/SynonymsIterator.cs

This is to iterate over all rules and synonyms in an index

Add RulesIterator and SynonymsIterators 

---

Algolia.Search.Test/AlgoliaClientTest.cs
Algolia.Search/Algolia.Search.csproj
Algolia.Search/AlgoliaClient.cs
Algolia.Search/Index.cs
Algolia.Search/Query.cs
ChangeLog

- Rename GetApiKeyACL to GetApiKey
- Add validUntil parameter
- Add RequestOptions to BrowseAll method

Fix misalignments between code and doc

---

Algolia.Search/Algolia.Search.csproj

Requirements were to download the developer packs so that it can run on the machine

Add support for .net 4.7 and .net 4.7.1

---

Algolia.Search.Test/AlgoliaClientTest.cs
Algolia.Search.Test/BaseTest.cs
Algolia.Search/AlgoliaClient.cs

Implemented 7 async+sync methods for the MCM endpoints #491

feat(mcm): add new MCM endpoints

---

Algolia.Search.Test/Algolia.Search.Test.csproj
Algolia.Search.Test/AlgoliaClientTest.cs
Algolia.Search.Test/BaseTest.cs
Algolia.Search/AlgoliaClient.cs
Algolia.Search/Analytics.cs

Introduce `Analytics` class to handle AB Test management.
See PR on PHP client for the details: algolia/algoliasearch-client-php#408

feat(analytics): Introduce Analytics class

---

Algolia.Search.Test/AlgoliaClientTest.cs
Algolia.Search.Test/IndexHelperTest.cs
Algolia.Search/Models/RuleQuery.cs

| New feature?      | yes 
| Related Issue     | no
Added the Enabled feature for Query rules v2
Added the Demote (Hide) test case
Added the TimeFrame test case
Added the Query Edits test case
Added Match the Empty Query test case
Added Disjunctive Facet Filters test case

Query Rules v2

---

.gitignore
Algolia.Search.Test/Algolia.Search.Test.csproj
Algolia.Search/Algolia.Search.csproj

| New feature?      | no   
Modified the csproj files to make it compliant with OSX env.

Added: OSX support for C# V5.2

---

README.md

Added the nuget badge to the readme

Added: nuget bade to readme

---

Algolia.Search.Test/AlgoliaClientTest.cs
Algolia.Search/Query.cs

| New feature?      | yes 
Add the missing parameters for personalization  on searchQuery

Added: enablePersonalization

---

src/Algolia.Search.Test/BaseTest.cs

Fixed: Test clean up not cleaning up all indices

---

src/Algolia.Search.Test/EndToEnd/Account/AccountCopyIndexTest.cs
src/Algolia.Search/Clients/AlgoliaConfig.cs
src/Algolia.Search/Clients/ISearchClient.cs
src/Algolia.Search/Clients/ISearchIndex.cs
src/Algolia.Search/Clients/SearchClient.cs
src/Algolia.Search/Clients/SearchIndex.cs
src/Algolia.Search/Iterators/RulesIterator.cs
src/Algolia.Search/Iterators/SynonymsIterator.cs
src/Algolia.Search/Transport/HttpTransport.cs

Fixed wrong methods signature.

Fixed: Wrong methods signature

---

src/Algolia.Search.Test/EndToEnd/Analytics/AnalyticsAATest.cs
src/Algolia.Search/Models/Analytics/Variant.cs
src/Algolia.Search/Models/Search/Query.cs

| New feature?      | Yes
| Need Doc update   | Yes
Added the AA testing feature and its related test.
You are now able to create an AA test on the same Index with optional custom search parameters

Added: AA Testing

---

src/Algolia.Search.Test/EndToEnd/ApiKeys/SecuredApiKeyTest.cs
src/Algolia.Search.Test/EndToEnd/Client/ApiKeysTest.cs
src/Algolia.Search/Clients/ISearchClient.cs
src/Algolia.Search/Clients/SearchClient.cs
src/Algolia.Search/Models/ApiKeys/RestoreApiKeyResponse.cs

| New feature?      | Yes
| Need Doc update   | Yes
Added the RestoreAPIKey method and the tests related to it.
Path: /1/keys/:key/restore
Method: POST
Body: none

Added: Restore API Keys

---

.gitattributes
editor.config

Adding the `.editorconfig` file and `.gitattribute` to the repository

Adding: .editorconfig and .gitattributes

---

src/Algolia.Search.Test/EndToEnd/Analytics/AnalyticsAATest.cs
src/Algolia.Search.Test/EndToEnd/Analytics/AnalyticsAbTest.cs
src/Algolia.Search/Models/Analytics/ABTest.cs
src/Algolia.Search/Models/Analytics/Variant.cs

Fixing parameters types in ABTest class.

Fixed: ABTest parameters validation

---

src/Algolia.Search/Clients/SearchIndex.cs

Missing URL encoding on parameters

Added: missing encoding on parameters

---

src/Algolia.Search/Models/ApiKeys/UpdateApiKeyResponse.cs

Fixes a typo on the summary of a UpdateApiKeyResponse

Fixes typo in UpdateApiKeyResponse

---

src/Algolia.Search.Test/RetryStrategyTest/RetryStrategyTest.cs
src/Algolia.Search/Clients/SearchConfig.cs
src/Algolia.Search/Transport/StatefulHost.cs

| Related Issue     | Fix #563 
Removed unused property.

Removed: unsued priority property

---

src/Algolia.Search.Test/Serializer/SerializerTest.cs
src/Algolia.Search/Models/Search/Query.cs
src/Algolia.Search/Utils/QueryStringHelper.cs

| Related Issue     | Fix #540 
Added the `ToQueryString()` in Query class.
`QueryStringHelper` was not correctly serializing List and nested List.

Added: ToQueryString() in Query class

---

src/Algolia.Search.Test/Algolia.Search.Test.csproj
src/Algolia.Search.Test/EndToEnd/Client/DnsTimeoutTest.cs
src/Algolia.Search.Test/EndToEnd/Index/QueryRulesTest.cs
src/Algolia.Search.Test/TestHelper.cs
src/Algolia.Search/Algolia.Search.csproj
src/Algolia.Search/Clients/AccountClient.cs
src/Algolia.Search/Clients/AnalyticsClient.cs
src/Algolia.Search/Clients/IAccountClient.cs
src/Algolia.Search/Clients/IAnalyticsClient.cs
src/Algolia.Search/Clients/IInsightsClient.cs
src/Algolia.Search/Clients/ISearchClient.cs
src/Algolia.Search/Clients/ISearchIndex.cs
src/Algolia.Search/Clients/InsightsClient.cs
src/Algolia.Search/Clients/SearchClient.cs
src/Algolia.Search/Clients/SearchIndex.cs
src/Algolia.Search/Clients/UserInsightsClient.cs
src/Algolia.Search/Http/AlgoliaHttpRequester.cs
src/Algolia.Search/Http/IHttpRequester.cs
src/Algolia.Search/Serializer/SerializerHelper.cs
src/Algolia.Search/Transport/HttpTransport.cs
src/Algolia.Search/Transport/IHttpTransport.cs

| Need Doc update   |no
Code clean up with c# 7.3 features

Code cleanup

---

.editorconfig
src/Algolia.Search.Test/EndToEnd/Account/AccountCopyIndexTest.cs
src/Algolia.Search.Test/EndToEnd/Client/CopyIndexTest.cs
src/Algolia.Search.Test/EndToEnd/Index/MultiClusterManagementTest.cs
src/Algolia.Search.Test/EndToEnd/Index/QueryRulesTest.cs
src/Algolia.Search.Test/EndToEnd/Index/ReplacingTest.cs
src/Algolia.Search.Test/EndToEnd/Index/SynonymsTest.cs
src/Algolia.Search.Test/EndToEnd/Insights/InsightsTest.cs
src/Algolia.Search.Test/Serializer/SerializerTest.cs
src/Algolia.Search.Test/TestHelper.cs
src/Algolia.Search/Clients/AccountClient.cs
src/Algolia.Search/Clients/ISearchIndex.cs
src/Algolia.Search/Clients/InsightsClient.cs
src/Algolia.Search/Clients/SearchIndex.cs
src/Algolia.Search/Http/AlgoliaHttpRequester.cs
src/Algolia.Search/Http/HttpRequestExtensions.cs
src/Algolia.Search/Models/Search/FacetStats.cs
src/Algolia.Search/Models/Search/Query.cs
src/Algolia.Search/Serializer/AutomaticFacetFiltersConverter.cs
src/Algolia.Search/Serializer/DateTimeEpochConverter.cs
src/Algolia.Search/Serializer/EditConverter.cs
src/Algolia.Search/Serializer/QuerySerializer.cs
src/Algolia.Search/Serializer/SerializerHelper.cs
src/Algolia.Search/Transport/RetryStrategy.cs
src/Algolia.Search/Utils/DateTimeHelper.cs
src/Algolia.Search/Utils/RequestOptionsHelper.cs
src/Algolia.Search/Utils/ShuffleHelper.cs

| Bug fix?          | yes/no
| New feature?      | yes/no    
| Related Issue     | Fix #...  
Adding `dotnet format` and `editorconfig` to the CI and the project

Add: dotnet format to the project + CI

---

src/Algolia.Search.Test/EndToEnd/Analytics/AnalyticsAATest.cs

Fixed: AA Testing flaky test

---

src/Algolia.Search.Test/EndToEnd/Index/IndexingTest.cs
src/Algolia.Search/Models/Search/Query.cs

- TagFilters is List<List<string>> instead of string
| BC breaks?        | yes     
| Related Issue     | Fix #573 

Fixed: TagFilters in query

---

src/Algolia.Search.Test/EndToEnd/Index/SettingsTest.cs

| Related Issue     | Fix #587 

Added: missing settings in settings test

---

src/Algolia.Search/Models/Search/Query.cs

| Related Issue     | Fix #574 
| Need Doc update   | No (already done)

Added: personalization impact in query

---

src/Algolia.Search/Clients/AlgoliaConfig.cs

Updated: headers

---

src/Algolia.Search/Models/ApiKeys/ApiKey.cs

| BC breaks?        | yes     
| Related Issue     | Fix #585

Removed: RestrictSources in APIKey

---

src/Algolia.Search/Models/Search/Query.cs

| Related Issue     | Fix #604 

Added: SimilarQuery as SearchParameter

---

src/Algolia.Search.Test/EndToEnd/Index/SettingsTest.cs
src/Algolia.Search/Models/Settings/IndexSettings.cs

| Related Issue     | Fix #600 
| Need Doc update   | yes (done)

Added: AttributeCriteriaComputedByMinProximity

---

src/Algolia.Search.Test/EndToEnd/Analytics/AnalyticsAbTest.cs
src/Algolia.Search/Clients/AnalyticsClient.cs
src/Algolia.Search/Clients/IAnalyticsClient.cs
src/Algolia.Search/Models/Analytics/ABTestsResponse.cs

| Related Issue     | Fix #597 
Typo in the class name.

Renamed: ABTestReponse -> ABTestResponse

---

src/Algolia.Search/Models/Settings/IndexSettings.cs

| Related Issue     | Fix #605

Added: primary in IndexSettings

---

src/Algolia.Search.Test/EndToEnd/Index/SettingsTest.cs
src/Algolia.Search/Models/Settings/IndexSettings.cs

| Related Issue     | Fix #601
| Need Doc update   | no already done

Added: userData in IndexSettings

---

src/Algolia.Search.Test/EndToEnd/Analytics/AnalyticsAATest.cs
src/Algolia.Search.Test/EndToEnd/Analytics/AnalyticsAbTest.cs
src/Algolia.Search.Test/EndToEnd/ApiKeys/SecuredApiKeyTest.cs
src/Algolia.Search.Test/EndToEnd/Client/ApiKeysTest.cs
src/Algolia.Search.Test/EndToEnd/Client/LogsTest.cs
src/Algolia.Search.Test/EndToEnd/Client/MultipleOperationsTest.cs
src/Algolia.Search.Test/EndToEnd/Index/BatchingTest.cs
src/Algolia.Search.Test/EndToEnd/Index/IndexingTest.cs
src/Algolia.Search.Test/EndToEnd/Index/MultiClusterManagementTest.cs
src/Algolia.Search.Test/EndToEnd/Index/QueryRulesTest.cs
src/Algolia.Search.Test/EndToEnd/Index/ReplacingTest.cs
src/Algolia.Search.Test/EndToEnd/Index/SearchTest.cs
src/Algolia.Search.Test/EndToEnd/Index/SynonymsTest.cs

This pr Improves assertions in the common test suite.

Internal: Improve test assertions

---

src/Algolia.Search/Http/AlgoliaHttpRequester.cs

Added a missing using block on the response stream.

fix: missing using block in HttpRequester

---

.editorconfig
src/Algolia.Search.Test/EndToEnd/Index/MultiClusterManagementTest.cs
src/Algolia.Search/Clients/SearchIndex.cs

- Removed unused code rules
- Fixed format warning

internal: formatting rules

---

src/Algolia.Search.Test/EndToEnd/ApiKeys/SecuredApiKeyTest.cs
src/Algolia.Search/Clients/ISearchClient.cs
src/Algolia.Search/Clients/SearchClient.cs

| Related Issue     | Fix #638 
See #638

Feat(is secured api key expired)

---

src/Algolia.Search.Test/EndToEnd/Index/SearchTest.cs
src/Algolia.Search/Clients/ISearchIndex.cs
src/Algolia.Search/Clients/SearchIndex.cs
src/Algolia.Search/Utils/AlgoliaHelper.cs

Deprecate and replace unit testing relevance

---

src/Algolia.Search.Test/Serializer/SerializerTest.cs
src/Algolia.Search/Models/Rules/ConsequenceParams.cs
src/Algolia.Search/Models/Rules/ConsequenceQuery.cs
src/Algolia.Search/Serializer/ConsequenceQueryConverter.cs

@spinach Since @Ant-hem is off right now, could you help me review this PR? If not, no worries.

fix(rule): correctly deserialize legacy 'remove' field in ConsequenceParams

---

src/Algolia.Search.Test/EndToEnd/Index/QueryRulesTest.cs
src/Algolia.Search/Models/Search/Query.cs

| Related Issue     | Fix #650
Added CTS test case for the new `context` feature.

internal(CTS): adds contextual rules test case

---

src/Algolia.Search.Test/EndToEnd/Analytics/AnalyticsAATest.cs
src/Algolia.Search.Test/EndToEnd/Client/DnsTimeoutTest.cs
src/Algolia.Search.Test/EndToEnd/Client/ExceptionsTest.cs
src/Algolia.Search.Test/EndToEnd/Client/LogsTest.cs
src/Algolia.Search.Test/EndToEnd/Index/MultiClusterManagementTest.cs
src/Algolia.Search/Clients/AlgoliaConfig.cs
src/Algolia.Search/Clients/AnalyticsConfig.cs
src/Algolia.Search/Clients/InsightsConfig.cs
src/Algolia.Search/Clients/SearchConfig.cs
src/Algolia.Search/Clients/SearchIndex.cs
src/Algolia.Search/Http/HttpRequestHeadersExtensions.cs
src/Algolia.Search/Models/ApiKeys/DeleteApiKeyResponse.cs
src/Algolia.Search/Models/ApiKeys/UpdateApiKeyResponse.cs
src/Algolia.Search/Models/Mcm/AssignUserIdResponse.cs
src/Algolia.Search/Models/Mcm/RemoveUserIdResponse.cs
src/Algolia.Search/Models/Rules/Alternatives.cs
src/Algolia.Search/Models/Search/HighlightResult.cs
src/Algolia.Search/Models/Search/SnippetResult.cs
src/Algolia.Search/Models/Synonyms/SynonymQuery.cs
src/Algolia.Search/Serializer/AlternativesConverter.cs
src/Algolia.Search/Utils/AlgoliaHelper.cs
src/Algolia.Search/Utils/Defaults.cs
src/Algolia.Search/Utils/QueryStringHelper.cs

Code clean-up of Algolia.Search & Algolia.Search.Test

internal: code clean-up 

---

src/Algolia.Search.Test/EndToEnd/Index/MultiClusterManagementTest.cs

| New feature?      |no
Fixing bug in the MCM test causing it to be flaky.

internal: fix MCM test flakiness

---

src/Algolia.Search.Test/EndToEnd/Index/MultiClusterManagementTest.cs

| Bug fix?          | yes (in test suite)
The MCM test case was not correctly removing past UserIDs, making CI to fail.

internal: fix MCM-test logic regarding removing of past UserIDs

---

src/Algolia.Search/Models/Mcm/SearchUserIdsRequest.cs

Makes Page and HitsPerPage nullabe in `SearchUserIDRequest`

fix: searchUserIDRequest nullable type

---

src/Algolia.Search.Test/EndToEnd/Index/MultiClusterManagementTest.cs
src/Algolia.Search/Clients/ISearchClient.cs
src/Algolia.Search/Clients/SearchClient.cs
src/Algolia.Search/Models/Mcm/AssignUserIdsRequest.cs
src/Algolia.Search/Models/Mcm/AssignUserIdsResponse.cs

| Related Issue     | Fix #660
This PR adds the `assignUserIDs` method and its related test suite

feat(MCM) - assignUserIDs

---

src/Algolia.Search.Test/EndToEnd/Index/QueryRulesTest.cs
src/Algolia.Search/Models/Rules/Consequence.cs

| New feature?      | yes/
| Related Issue     | Fix #670 
adds the`filterPromotes` parameter to QueryRule

feat(query_Rules): filterPromotes

---

src/Algolia.Search/Models/Settings/IndexSettings.cs

| Related Issue     | Fix #671 
adds `customNormalization` to `IndexSettings`.
The test is expected to fail at the moment because feature is still in beta.

feat(index_settings): customNormalization

---

src/Algolia.Search.Test/EndToEnd/Index/MultiClusterManagementTest.cs
src/Algolia.Search/Clients/ISearchClient.cs
src/Algolia.Search/Clients/SearchClient.cs
src/Algolia.Search/Models/Mcm/HasPendingMappingsResponse.cs

| Related Issue     | Fix #678 
adds: the `HasPendingMappings` method to `SearchClient`.

feat(mcm): has pending mappings

---

src/Algolia.Search.Test/BaseTest.cs
src/Algolia.Search.Test/EndToEnd/Recommendation/RecommendationClientTest.cs
src/Algolia.Search.Test/Serializer/SerializerTest.cs
src/Algolia.Search/Clients/IRecommendationClient.cs
src/Algolia.Search/Clients/ISearchClient.cs
src/Algolia.Search/Clients/RecommendationClient.cs
src/Algolia.Search/Clients/RecommendationConfig.cs
src/Algolia.Search/Clients/SearchClient.cs
src/Algolia.Search/Models/Personalization/EventScoring.cs
src/Algolia.Search/Models/Personalization/FacetScoring.cs
src/Algolia.Search/Models/Personalization/GetStrategyResponse.cs
src/Algolia.Search/Models/Personalization/SetStrategyRequest.cs
src/Algolia.Search/Models/Personalization/SetStrategyResponse.cs
src/Algolia.Search/Models/Recommendation/EventsScoring.cs
src/Algolia.Search/Models/Recommendation/FacetsScoring.cs
src/Algolia.Search/Models/Recommendation/GetStrategyResponse.cs
src/Algolia.Search/Models/Recommendation/SetStrategyRequest.cs
src/Algolia.Search/Models/Recommendation/SetStrategyResponse.cs

| New feature?      | yes/
| Related Issue     | Fix #681 
- Deprecates legacy personalization endpoint
- adds new RecommendationClient

feat(api) introducing recommendation client

---

src/Algolia.Search.Test/EndToEnd/Index/MultiClusterManagementTest.cs

Fix flakyness of the MCM test.

fix(MCM): test flakyness

---

src/Algolia.Search.Test/BaseTest.cs
src/Algolia.Search.Test/EndToEnd/Account/AccountCopyIndexTest.cs
src/Algolia.Search.Test/EndToEnd/Client/MultipleOperationsTest.cs
src/Algolia.Search.Test/EndToEnd/Index/QueryRulesTest.cs
src/Algolia.Search.Test/EndToEnd/Index/ReplacingTest.cs
src/Algolia.Search.Test/EndToEnd/Index/SearchTest.cs
src/Algolia.Search.Test/Serializer/SerializerTest.cs
src/Algolia.Search/Serializer/ConsequenceQueryConverter.cs

Apply formatting on the code base with `dotnet format -w src`

chore: formatting

---

src/Algolia.Search/Models/Search/Query.cs

| Related Issue     | Fix #699 
adds the `naturalLanguages` parameter.

feat(query): adds naturalLanguages parameter

---

src/Algolia.Search.Test/EndToEnd/Recommendation/RecommendationClientTest.cs

test(recommendation): update CTS test with SetPersonalizationStrategy call

---

README.md

| Bug fix?          | yes/no
| New feature?      | yes/no    
| Related Issue     | Fix #...  
Updates readme with circle ci badge

chore: update readme with Circle CI badge

---

src/Algolia.Search.Test/EndToEnd/Index/SettingsTest.cs
src/Algolia.Search/Models/Settings/IndexSettings.cs

feat: add EnablePersonalization setting parameter

---

src/Algolia.Search.Test/Serializer/SerializerTest.cs
src/Algolia.Search/Models/Enums/PartialUpdateOperationType.cs
src/Algolia.Search/Models/Search/PartialUpdateOperation.cs

feat(indexing): built-in operations 'IncrementFrom' and 'IncrementSet'

---

src/Algolia.Search.Test/EndToEnd/Recommendation/RecommendationClientTest.cs

fix(personalization_strategy): prevent error in CTS personalization test on 429 HTTP code

---

src/Algolia.Search.Test/EndToEnd/Client/ExceptionsTest.cs
src/Algolia.Search/Clients/SearchIndex.cs

| New feature?      | no   
| Related Issue     | Fix #732   
- Updated message thrown by ArgumentNullException
- Update tests related to exception thrown 
This related to this issue #731 where the error message wasn't detailed enough.

Fix: enhance error message when list is empty

---

src/Algolia.Search.Test/EndToEnd/Index/SettingsTest.cs
src/Algolia.Search/Models/Settings/IndexSettings.cs

| New feature?      | yes  
| Related Issue     | Fix #753   
This PR adds:
* attributeToTransliterate settings parameter
* tests

feat(settings): add new index attributesToTransliterate settings

---

src/Algolia.Search.Test/Algolia.Search.Test.csproj

Possible fix for reported issue https://github.com/nunit/nunit/issues/2772#issuecomment-448912055

chore(test): Update Algolia.Search.Test deps

---

src/Algolia.Search.Test/EndToEnd/Index/SettingsTest.cs
src/Algolia.Search/Models/Search/Query.cs
src/Algolia.Search/Models/Settings/IndexSettings.cs

| New feature?      | yes  
| Related Issue     | Fix #752    
This PR adds:
* DecompoundQuery settings parameter
* tests

feat(settings): add new DecompoundQuery settings

---

.github/CODEOWNERS

| Related Issue     |  
Update ownership of the repository

chore: update ownership

---

src/Algolia.Search.Test/EndToEnd/Index/QueryRulesTest.cs
src/Algolia.Search/Models/Rules/Condition.cs

| New feature?      | yes   
| Related Issue     | Fix #755  
| Jira Tickect |[DX-1779]( https://algolia.atlassian.net/browse/DX-1779)
This pull request add `Filters` as field in condition for query rules

Feat: add filter query rule condition

---

MAINTAINERS.md

| Related Issue     | 
Update maintainer.md file
None

Chore: update maintainer file

---

DOCKER_README.md
Dockerfile
README.md

| New feature?      | yes    
| Related Issue     | Fix #747   
| Need Doc update   |no
- Add DockerFile
- Add DockerReadme
- Update readme
This pull request add the possibility of the user of running this library without installing dependancies or system requirement

feat: containerize our repository

---

src/Algolia.Search/Transport/RetryStrategy.cs

there was a typo in the docblock
Aloglia is not how you spell Algolia

docs(retry): fix typo aloglia

---

README.md

Clarify the README with .NET Standard compatibility.

docs: update README.md with .NET Standard compat

---

src/Algolia.Search/Clients/SearchIndex.cs

We blindly merged #816, assuming there couldn't be an error in such a small change :)

fix: syntax error

---

.circleci/config.yml

| Bug fix?          |no
| Related Issue     | Fix #...  
| Need Doc update   |no

chore(ci): increase e2e test timeout 
